# ==========================
# Application Configuration
# ==========================

baseUrl=http://localhost:5173/login

# Browser
browser=chrome

# Waits
implicitWait=10
explicitWait=20

# Window
maximize=true

# ==========================
# Login Credentials
# ==========================

adminEmail=admin@gmail.com
adminPassword=admin123

employeeEmail=employee@gmail.com
employeePassword=employee123